spring:
  application:
    name: ESGInsightBoard
  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql
  # Flyway 설정
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    out-of-order: true
    clean-disabled: false
    clean-on-validation-error: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      fail-on-empty-beans: false
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

server:
  port: 8080

# Springdoc OpenAPI 설정
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
    doc-expansion: none
    default-models-expand-depth: -1
    show-extensions: true
    url: /api-docs
    config-url: /api-docs/swagger-config
    hide-empty-tags: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**

# JWT 설정  
jwt:
  header: Authorization
  prefix: Bearer
  secret: ${JWT_SECRET:}  # 환경 변수에서 시크릿 키를 가져오거나, 비어있으면 자동 생성
  expiration: 86400000  # 24시간 (밀리초)

# 프로필 설정
---
spring:
  config:
    activate:
      on-profile: dev
  flyway:
    clean-disabled: false
    clean-on-validation-error: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

---
spring:
  config:
    activate:
      on-profile: prod
  flyway:
    clean-disabled: true
  jpa:
    hibernate:
      ddl-auto: validate
